[package]
name = "core-voice"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
core-atvv = { path = "../core-atvv" }
core-audio = { path = "../core-audio" }
core-log = { path = "../core-log" }

[dev-dependencies]

[target.'cfg(windows)'.dependencies]
core-ble = { path = "../core-ble" }
core-input = { path = "../core-input" }
core-hid = { path = "../core-hid" }
